post https://urwallpaper-react-x2el.vercel.app/user-api/user
Content-Type: application/json

{
    "username":"Thrinath",
    "password":"22501A05E9"
}

###
post https://urwallpaper-react-x2el.vercel.app/user-api/login
Content-Type: application/json

{
    "username":"Thrinath",
    "password":"22501A05E9"
}

###
get https://urwallpaper-react-x2el.vercel.app/image-api/get-images

###
delete https://urwallpaper-react-x2el.vercel.app/image-api/delete-image/wallpapers%2Fkvq0llpxakul1lh9nso5